// Capture lock query + cap-name <-> bit-index mapping.
//
// The bit-index table (capture_table.h) is generated by
// scripts/sync_capture_table.ps1 from apworld/data/items.json so the Switch
// and bridge cannot drift on cap-name <-> id assignment.

#pragma once

#include <cstdint>
#include <string>

namespace smoap::game {

// Returns the bit index for `cap_name` (matching apworld's enemy ordering)
// or 0xff if the name is unknown.
std::uint8_t captureBitFor(const char* cap_name);

// M6 phase B: write `hack_name` into SMO's hack dictionary so the capture
// shows as unlocked in the compendium (and is treated as known by gameplay).
// Idempotent — probes isExistInHackDictionary first; the GameDataFunction
// API itself is a no-op on duplicates anyway.
//
// Inputs:
//   cap_name  — apworld-canonical cap name (e.g. "Goomba"). Used for logging.
//   hack_name — raw SMO hack name (e.g. "Kuribo"). What goes into the game.
//
// Returns true iff the dict entry exists after the call (either we wrote it
// or it was already present). Returns false when the write was dropped —
// callers (notably ApState::applyOnFrame) use this to defer the Cappy
// message and queue the item for the per-frame reconciler to retry.
//
// Call from the game frame thread only. Requires the GameDataHolder* cache
// in ApState to be populated (DrawMainHook does this every frame). When the
// cache is null (boot, scene transition, fresh save load), the first
// post-HELLO ItemMsg drain can race ahead of the first DrawMainHook cache
// update — that's the "GoombaCappy bubble fired but compendium empty" bug.
// The reconciler in reconcileCaptureDictionary heals it the next frame
// regardless.
//
// resolveCaptureGrantSymbols() must be called once at module init (from
// installCaptureGrantSymbols below) to bind the GameDataFunction:: function
// pointers via nn::ro::LookupSymbol. If the lookup fails, grantCapture logs
// and returns false.
bool grantCapture(const char* cap_name, const char* hack_name);

// Per-frame reconciliation. Walks ApState::captures_unlocked; for every set
// bit whose hack_name is missing from the in-game dictionary, attempts the
// addHackDictionary write. Bails as a single cheap pointer-load when the
// GDH cache or symbols aren't ready yet — safe to call every frame.
//
// Healing path for the silent-failure race in grantCapture: when an AP
// capture item arrives before DrawMainHook has cached the GameDataHolder
// pointer, the in-line grantCapture call drops. The bit stays set in
// captures_unlocked, and this reconciler picks it up on the next frame
// where the cache is populated. Frame-thread only.
void reconcileCaptureDictionary();

// True iff the player's hack dictionary already contains `hack_name`. Used
// by the ApState capture arm to suppress the Cappy bubble + skip the
// grantCapture call on bridge HELLO replays (initializeData fires many
// times per save-load, each causing a re-HELLO that re-ships every owned
// capture). Returns false in any degraded state — symbols unresolved or
// GameDataHolder not cached yet — so we fall through to the existing
// behavior (enqueue + grant) rather than silently dropping a real grant
// during early boot. Frame thread only (same constraints as grantCapture).
bool captureAlreadyInDictionary(const char* hack_name);

// Resolve the addHackDictionary + isExistInHackDictionary symbols once at
// module init. Wired from main.cpp alongside the existing softInstall calls.
void installCaptureGrantSymbols();

// True if the player has *not* received the unlock item for this capture.
bool captureBlocked(const char* cap_name);

// Resolve the capture's canonical name from a PlayerHackData / hack-target.
// (Implementation pulls from sead string tables in the game.)
std::string nameForHackData(/* const PlayerHackData* data */);

// Plays the standard "no" SE used by the game when something is denied.
void playSE_NG();

// M4.5 reconciliation: enumerate every capture (hack) the player has currently
// unlocked AND has used at least once. Worker-thread call from
// ApClient::sendSnapshot. Emits raw hack_names that the bridge resolves via
// capture_map.json.
//
// Stub for M4.5; M5/M6 fills in via GameDataHolder. The current ApState
// captures_unlocked bitset only tracks AP-granted captures, not save-state.
using CaptureEnumerationCallback = void(*)(void* ctx, const char* hack_name);
void enumerateOwnedCaptures(CaptureEnumerationCallback cb, void* ctx);

}  // namespace smoap::game
